on:
  workflow_dispatch:

jobs:
  cbom-scan:
    runs-on: ubuntu-20.04
    name: CBOM generation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: cbom scan
        id: scan
        uses: n1ckl0sk0rtge/cbom-scan-action@v0.0.15
